import Bootstrap from "@/components/libs/Bootstrap";
import "./globals.css";
import Header from "@/components/modules/Header/Header";
import ToastContainer from "@/components/Toastify/Toastify";
import Footer from "@/components/modules/Footer/Footer";
import ProgressProviders from "@/components/libs/ProgressBarProvider";
import { AuthProvider } from "@/utils/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
        <ProgressProviders>
          <Header />
          {children}
          <Footer />
          <Bootstrap />
          <ToastContainer />
        </ProgressProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
