import Bootstrap from "@/components/libs/Bootstrap";
import "./globals.css";
import Header from "@/components/modules/Header/Header";
import ToastContainer from"@/components/Toastify/Toastify"
import Footer from "@/components/modules/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header/>
        {children}
        <Footer/>
        <Bootstrap/>
        <ToastContainer/>
      </body>
    </html>
  );
}
